-- https://github.com/microsoft/vscode/blob/main/src/vs/base/common/codicons.ts
-- go to the above and then enter <c-v>u<unicode> and the symbold should appear
-- or go here and upload the font file: https://mathew-kurian.github.io/CharacterMap/
-- find more here: https://www.nerdfonts.com/cheat-sheet

return {
	ui = {
		Lock = "",
		TinyCircle = "",
		Circle = "",
		BigCircle = "",
		BigUnfilledCircle = "",
		CircleWithGap = "",
		LogPoint = "",
		Close = "",
		NewFile = "",
		Search = "",
		Lightbulb = "",
		Project = "",
		Dashboard = "",
		History = "",
		Comment = "",
		Bug = "",
		Code = "",
		Telescope = " ",
		Gear = "",
		Package = "",
		List = "",
		SignIn = "",
		Check = "",
		Fire = " ",
		Note = "",
		BookMark = "",
		Pencil = " ",
		ChevronRight = ">",
		Table = "",
		Calendar = "",
		Line = "▊",
		Evil = "",
		Debug = "",
		Run = "",
		VirtualPrefix = "",
		Next = "",
		Previous = "",
	},
	diagnostics = {
		Error = " ",
		Warning = " ",
		Information = " ",
		Question = " ",
		Hint = " ",
	},
	misc = {
		Robot = "ﮧ ",
		Squirrel = "  ",
		Tag = " ",
	},
}
